[project]
name = "auto-ria-scrap"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.2",
    "asyncpg>=0.30.0",
    "beautifulsoup4>=4.13.4",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "lxml>=5.4.0",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.41",
]
