"""initial migration

Revision ID: 2d09d4343933
Revises: 
Create Date: 2025-06-25 14:53:34.174407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d09d4343933'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_car',
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=65), nullable=False),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.String(length=255), nullable=False),
    sa.Column('car_vin', sa.String(length=255), nullable=False),
    sa.Column('datetime_found', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_number', 'url', name='uq_car_number_url')
    )
    op.create_index(op.f('ix_parse_car_id'), 'parse_car', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parse_car_id'), table_name='parse_car')
    op.drop_table('parse_car')
    # ### end Alembic commands ###
